### ISSUE TITLE
Floating Action Button has a problem on iOS project.

### ISSUE THREAD

**Issue by homerokzam** [keannan5390/xamarin-plugins#1]
IOS project files are not in the repository.

**Comment by sidNee** [comment]
The Forms.Fab doesn't work on ios for me, too :(

**Comment by davidtan24747** [comment]
Hi, this doesn't seem to work on iOS for me as well

**Comment by ghost** [comment]
sorry for the really long delay in fixing this. i just push changes that added the ios project back to the samples folder. It should work now when you load/build/run the solution.
