### ISSUE TITLE
Not recognised when initialising from iOS AppDelegate

### ISSUE THREAD

**Issue by chris247474** [keannan5390/xamarin-plugins#2]
Hi, `InitControl()` in ff line doesn't seem to be recognised in the iOS AppDelegate's FinishedLaunching method:

`FAB.iOS.FloatingActionButtonRenderer.InitControl ();`

I've tried updating Xamarin Forms to the latest release (2.2.0.3) and reinstalling the FAB.Forms Nuget (1.0.0.1) , but no luck. 

Thanks

**Comment by chris247474** [comment]
So I experimented and found that `new FAB.iOS.FloatingActionButtonRenderer();` seems to do the trick on iOS. Please disregard this issue

**Comment by chris247474** [comment]
I'm not sure how to close this issue, maybe only the project owner's can do that?

**Comment by ghost** [comment]
@chrisdavetv closed
