### ISSUE TITLE
Click not working on iOS (Xamarin.Forms 2.3.0.38-pre2)

### ISSUE THREAD

**Issue by rmenezes** [keannan5390/xamarin-plugins#3]
I'm trying to develop an app using the lib FAB but the event Click is not working on iOS using  Xamarin.Forms 2.3.0.38-pre2, works fine on Android. 

Also the method FloatingActionButtonRenderer.InitControl() is not available.

**Comment by ghost** [comment]
@rmenezes this should be fixed with the recent changes

**Comment by rmenezes** [comment]
@keannan5390 you will release this fix as nuget package? 

tks.

**Comment by ghost** [comment]
@rmenezes just released a new version of the package. I apologize lengthy delay in releasing fixes. 

version 2.0.0 should work for you.
