### ISSUE TITLE
After perfect nuget install, assembly still appears unavailable in project

### ISSUE THREAD

**Issue by brittonbeckham** [keannan5390/xamarin-plugins#4]
@keannan5390 I have tried everything to get this assembly to work, but it will not. I have installed the nuget numerous times and the install works fine, but the assembly appears to be unavailable, even though it's right there on disk and the project file points right to it:

![image](https://cloud.githubusercontent.com/assets/7856371/15638673/b2238ff8-25df-11e6-8f3f-876821e42418.png)

![image](https://cloud.githubusercontent.com/assets/7856371/15638681/c68a7b64-25df-11e6-9e7b-384bda72b914.png)

Then when I double-click the assembly reference I get this error. 

![image](https://cloud.githubusercontent.com/assets/7856371/15638684/ccaea0e2-25df-11e6-93f7-6cf9a7add806.png)

**Comment by ghost** [comment]
@brittonbeckham this should be addressed & fixed with the newest package in version: 2.0.0.

**Comment by brittonbeckham** [comment]
@keannan5390, I wanted to tell you that I did get your older version 1.0.0.1 or something to install, but after literally hours of attempting to get it to work properly on a ListView, it just wouldn't render in the right location consistently (weird?). I was wondering if you could get work up a sample for using in a Layout that has a ListView on it, -- perhaps you will discover the issues I am speaking about. This would be greatly appreciated.

**Comment by ghost** [comment]
I haven't tried with a listview yet. I can give it a shot though, I think I should have some time tomorrow.

**Comment by brittonbeckham** [comment]
Any luck on the ListView attempt? It's a shame Xamarin hasn't made this available out of the box.

**Comment by ghost** [comment]
@brittonbeckham, I guess i'm not sure exactly what you're trying to do. If you just want the FAB on the same screen as a ListView you should just be able to use the sample in the repo and replace the StackLayout with the ListView. If it's wrapped in a RelativeLayout it shouldn't change it's location.

``` xml
<ContentPage
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:fab="clr-namespace:FAB.Forms;assembly=FAB.Forms"
    x:Class="FABSample.XamlExample">
    <ContentPage.Content>
        <RelativeLayout>
            <ListView
                RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1}"
                RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=1}"
                ItemsSource="{Binding MyItems}">
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <TextCell Text="{Binding MyText}">
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
            <fab:FloatingActionButton
                Source="plus.png"
                Size="Normal"
                RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1, Constant=-60}"
                RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=1, Constant=-60}" />
        </RelativeLayout>
    </ContentPage.Content>
</ContentPage>
```

**Comment by brittonbeckham** [comment]
I apologize for not being more specific. There appears to be a rendering issue when using it with a ListView in this manner. I tried once again with your updated version 2.0 and it still has the same problem.

It cuts the shadow off at the bottom (and possible sides?) for no reason:
![image](https://cloud.githubusercontent.com/assets/7856371/15996055/ba13954e-30e0-11e6-9397-feaf1800e44b.png)

![image](https://cloud.githubusercontent.com/assets/7856371/15996088/0fb42a40-30e1-11e6-94ec-f3932af95976.png)

Here is my xaml:

``` html
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:controls="clr-namespace:FAB.Forms;assembly=FAB.Forms"
             x:Class="Prepify.App.Pages.Inventory.Lists"
                         BackgroundColor="White"
                         Icon="ic_assignment_white_24dp.png"
                         Title="Lists">

    <ContentPage.ToolbarItems>
        <ToolbarItem Icon="ic_add_white_48dp" Clicked="Add_OnClick"  />
        <ToolbarItem Icon="ic_search_white_24dp" Clicked="Search_OnClick" />
    </ContentPage.ToolbarItems>

    <RelativeLayout>
        <ListView
                RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1}"
                RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=1}"
                ItemsSource="{Binding .}"
                Style="{StaticResource listViewDefaultStyle}"
                ItemSelected="ItemSelected"
                x:Name="lvLists">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <StackLayout Orientation="Horizontal" Padding="15, 5, 15, 5" VerticalOptions="CenterAndExpand">
                            <Image Source="{Binding Icon}" />
                            <Label Text="{Binding Name}" VerticalOptions="Center" HorizontalOptions="StartAndExpand" FontSize="20" />
                            <Label Text="{Binding AcquiredFraction}" HorizontalTextAlignment="End" HorizontalOptions="End" FontSize="14" VerticalOptions="Center"/>
                            <Image Source="ic_chevron_right_black_24dp" HorizontalOptions="End" />
                        </StackLayout>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
        <controls:FloatingActionButton
                                        Source="ic_add_white_48dp"
                                        Size="Normal"
                                        NormalColor="{StaticResource accentColor}"
                                        RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1, Constant=-80}"
                                        RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=1, Constant=-80}" />
    </RelativeLayout>
</ContentPage>
```

**Comment by brittonbeckham** [comment]
I pulled the repo down last night a spent about an hour or so trying to get the shadow to show up properly but couldn't make any progress. It's like it is clipping it or something, but tweaking values and sizes didn't make much of a difference.  Let me know if you can pinpoint it. Thanks.

**Comment by ghost** [comment]
@brittonbeckham I'm not sure of the exact cause for this display issue you're experiencing. It seems to be related to the clipping of the FAB by the parent view when above a list view. I was able to solve this by wrapping the ListView in a ContentView within the RelativeLayout. 

I've moved the FAB project to it's [own repository](https://github.com/keannan5390/Xamarin.Plugin.FAB). In the repo I created a sample with a listview that works around the problem you showed above.

**Comment by brittonbeckham** [comment]
Thanks, your workaround works better than mine, as my listviews didn't scroll properly.
