### ISSUE TITLE
FAB AND iOS

### ISSUE THREAD

**Issue by sidNee** [keannan5390/xamarin-plugins#5]
how to use Floating Action button with ios and XAML?

**Comment by sidNee** [comment]
Please write a how to for implementing FAB for iOS in Xamarin.Forms.....

**Comment by ghost** [comment]
hi @sidNee, the newest version of the nuget package should work on iOS now.

As for a XAML example, you can reference one [here](https://github.com/keannan5390/xamarin-plugins/blob/master/FloatingActionButton/Sample/FABSample/XamlExample.xaml)
